language: scala

script:
 - sbt clean coverage test coverageReport
 - sbt coverageAggregate
 - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && sbt publish'

scala:
 - 2.11.8

jdk:
 - oraclejdk8

after_success:
 - sbt coveralls

env:
  global:
   - secure: r6SM4/Kkf9PYzYkQYPEcvy06oL2/mtSkNWIGsECSV2p6KtYhBWl2cOsGDVusukAoaOmnlD+jFYfg6NGk2gkZLwB07vu3i3Cmaj6WNFROTR82macD5y5dMyAu5Oz+ML24thqzD2sOcKGNQUqv8Sk/C9sph9D38bIwnXKyhcf55mP8WF6CoYHg9Pivsah33ljlxN2g/ty8AKmsVhaXORe7SFl34bIWOlggWWJqmlVLT3+FcO8HBmoDMYSOj53g1e6HXl6Wf0hwwFcisB6pYoGUBlLzJ1eM73U/dxZOLTFFd54sjX4c8E9f0trsc0xUNc/d+D+F346iiCV4RzPOvcWDIpdXlYSHJPqbsCt3lJl6LxKrBXf2ALRbzywChudDcovLvyiUNf45cyHxH1HiAbHGM9JDB0OYJNMuEPJtEA3Jw//4vwngkFsDLCZVYAup49NQRTOkcKnNFJZjl3SlAq9siYzLdNkHHAVEmEfJksJZXXjYIOLBllO6v1HfeQwTm1UxFaKarEczNngP8re+m/L2ItUq9iU/zZKlyM/hzdtXg5CUoLlsa3L7es2EaHy/9QKTciMsWAobSHA6wub2d71cI92SNsXvuPdlOdgvwkcUJIAHuzJnhnTCDDxtwPz1MvbCBOSKcHo9qsrs4rdzzsLxX1nzrmFEsqUTQaIWf5uHBR4=
   - secure: cokqnbeFz+glqof86nX0q9UmjHiqggyqXzzt9hYbtbbdSF2BA0aW7slx6DDRJwCQTr4vqEhOyVNLppO0iA35ll/hUJXmZ1fOcySblPbCZUbe1+Fy3/Z+0OI3UtSiYw7Wt+usOurounkjmdR2oEwxVhcODC3Cg0Un7yNycR25jd5LHVWCKuiGOlnDTy1JnaNth1sxU/N3hDdvx263KOOXMZeaMJ5tYPX5wOBCNioPOVwhmcv/atXrxGSK9m5auVKiGfvzi4gzbJnoBW5qyJKNd0keXeWR8SX02vFTqBSUXYAJxpoJ+LVUTr2YCvg5D0kRDwJHThcrNiTctz4rZpp/Ty93LR+O13I4ItN97pAVUOr8kIGl41hjNndv0ulFfdgd8x27JRwyhxDMavxxuk+/9dnOzTNyOp73Dyhlnl5O3wJvPJWiXqTyoczvD1Uqsewp5If72S1fpgNdkpKRdsFkZ7+UGRaL2+fl2TZ6DnM96G2//mAMvxg/LL3ExJhlBwV2o4in06ZkWRrMFyuZnlFh2wv0GykFx0duqlKfWzG0z4dmKu0lGDmWCaWXNuwrKtnNa+35BlafNWs5231baPtQEotLkHnEl2KZ9T/QpbT8oxdKh1kGECkvcucPWz7rjUx1WsEa5/d4gV0zi5e0r6tTHWbNFutBEhvdd3hcFevIUFM=
