language: scala

script:
 - sbt clean coverage test coverageReport
 - sbt coverageAggregate
 - sbt publish

scala:
 - 2.11.8

jdk:
 - oraclejdk8

after_success:
 - sbt coveralls

env:
  global:
  - secure: a6gYNmtF1ZOzj9dka89jYZCsadtXuLSXDCU7QECBe+pksdv07ZZCNPZwrRbS/7X2WMbqjzAviChsqyiIwS+FhMngnO3iSHCKcemUPjLcySu6jwCsGRXVX+cqQe0ngm+I5Rf1jQ9GzuPv/Ne+4obyOMwmjIW3fObi1FYvVOi96agKmK/xGdtMEontNa3eBo9YyPvniakXEkTza1tATs/0HTXPYu801B3S1QDVm530CJlGXRooPo7MS3fXxFkiNzvNL8FO5MyS8gCz+f+h4zITFkxJLpBVxN5ZqkPo2k/nCmSC8mRuLPjC4mwGUhw+1VEaGg23Zebr6mF9w624nrYN9UPJBXZjJf36uARFpBlygwVeo3qn0D/nK2ZkDGiDyfc8LvjNjcBVwe5ScEZDhUGJeTt86bN8YJUE2d5A5Gn2nGGz4uICOL6YW3S87GtNemLSHHsHrQBIWngAEo5EPABobBTgqOfIOzIZkTOmfux0Es/fCHakQEkzUeinjo2Od1N77jA8XyGpJJZ2MEFLKI1h+E34KNW40h5xwg8iOYCZ6eFMJfUG9WxE9CRi4j/VhY7yMDFATlyzX38oyQtGCjoBsMGmzR2hS4B+rEk82yDvmCKXUzRhxODbzayqNlRKIOZoEZPYylK1EILgn9bVlqhKLyDB9MZiyu7Mk8uCv/hdJ+U=
  - secure: frr+v/rvWlTP0F/SSaGfOVtzh/+WswTmlwXrbCTVcsCLFQkP9amEgNrMpmXDuFyeofkPgOmLtHuS89hexiJlIAOcnbujAv6nCWHXkVKc9iViATbmi1uKG1hapAmdZcHGqxVJx97oipnWSySVrGw03fT0eUICuySAC6DnnCPJpblVpv6N0vKnpt1F/Jry29+4NclW20CHyEH8B9U9Be3QVA1Qb0Rvo3Pjvb8WwSZKLL95T+wLBY/9M+/l9Jfr9xuZKTpP2PpIMG+0VDoQsPRzP/oxvSSPMgnhYh7t1CCkYZ8ksWU6ui0neH9pc4Gua35kxRwvFhEb9C4vTggF7FmDG7ZyHfrK8oG5fbWyl+iMq8OPaqaanopSMZcoKosIq00K4aZz//SEC8SEigDwS7Gc99/f3ysN9EPg7LLTsM77LK9wL3ZkXa6HiqDB3GLYcjWBZvvCdq5U4NJFlFSTbpjK4Ar286NNReuljKyarGACKjs5E/cLlX3T0Hqxzrjzh0SpFSkIYGKM46wdFYzaDUdO5pqJCaZunWzRDcOvMNf7ZTL6bQ7DgpTeUszI/9kAt3uxoLUVRQaH6iDC2v6XkDrmMHfuR/p7Ky2hh908CoRxN7zisVi4dWReIrRu/NPqVUgYE141O9mCkaWCrlkQjoRNAkoYhet5SR7TkaEPYxcKpBw=
